### PR TITLE
test tests.yml

### PR DESCRIPTION
**Pull request by TrevorJTClarke**

### CODE REVIEW

**Comment by ctindogaru** [comment]
Hey Trevor, is this to be merged?

**Comment by TrevorJTClarke** [comment]
> Hey Trevor, is this to be merged?

Im trying to narrow down why the ci/cd is failing - when everything runs locally and is fine, the ava tests have issues

**Comment by ctindogaru** [comment]
Where do you see them failing?

You get `    message: 'Can not sign transactions for account test.near on network sandbox, no matching key pair found in InMemorySigner(UnencryptedFileSystemKeyStore(/tmp/sandbox/b7a63273-5c84-400a-ab6f-340ab73c294b)).',
` error from time to time if you push too many commits in a short time, but other than that they pass pretty much every time.

**Comment by TrevorJTClarke** [comment]
@ctindogaru yes thats the exact error. Is it fixable? Kinda shitty that it fails sometimes because.... shrug?

**Comment by ctindogaru** [comment]
Yeah, it's shitty, I usually restart the job if it happens.

For me, it happens even locally (pretty frequent). It might be a problem with the `near ava` testing framework.

**Comment by TrevorJTClarke** [comment]
Got it - well im going to play with a couple ideas, and then i'll know what the issue is here.

**Comment by ctindogaru** [comment]
Fingers crossed. 🤞

**Comment by TrevorJTClarke** [comment]
hehe exactly 📦

**Comment by TrevorJTClarke** [comment]
welllllll that worked :D

**Pull request merged**
